[ruby-plus-devkit]
build_targets = [
  "x86_64-windows"
]
plan_path = "ruby-plus-devkit"

[ruby25-plus-devkit]
build_targets = [
  "x86_64-windows"
]
plan_path = "ruby25-plus-devkit"

[ruby27-plus-devkit]
build_targets = [
  "x86_64-windows"
]
plan_path = "ruby27-plus-devkit"

[ruby30-plus-devkit]
build_targets = [
  "x86_64-windows"
]
plan_path = "ruby30-plus-devkit"
